---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
spec:
  volumeName: pv-volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
  labels:
    app: data-exchange
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      volumes:
      - name: myapp-volume
        persistentVolumeClaim:
          claimName: pvc-volume
      containers:
      - name: busybox
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            echo "Starting busybox writer..."
            mkdir -p /output
            while true; do
              echo "$(date): text test text test" >> /output/test-file.txt
              sleep 5
            done
        volumeMounts:
        - name: myapp-volume
          mountPath: /output
      - name: multitool
        image: wbitt/network-multitool
        command:
          - /bin/sh
          - -c
          - |
            tail -f /input/test-file.txt
        volumeMounts:
        - name: myapp-volume
          mountPath: /input